services:
  # Clip Generator Microservice
  clip-generator:
    build:
      context: ../clip-generator
      dockerfile: Dockerfile
    container_name: clip-generator
    ports:
      - "8001:8001"
    env_file:
      - ../clip-generator/.env
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8001
      - TEMP_DIR=/tmp/video_processing_host  # Usar directorio del host
      - DOWNLOAD_CHUNK_SIZE=524288       # 512KB chunks (m치s estable para archivos grandes)
      - MAX_VIDEO_SIZE_MB=5120           # 5GB m치ximo
      - PROGRESS_LOG_INTERVAL=50         # Log cada 50MB
      - LOG_LEVEL=INFO
    volumes:
      - temp_storage:/tmp/video_processing
      - ./temp_video_processing:/tmp/video_processing_host  # Volumen en host para videos grandes
    networks:
      - reelify-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8001/health')"]
      interval: 60s  # Aumentado para videos largos
      timeout: 30s   # M치s tiempo para responder
      retries: 5     # M치s reintentos
      start_period: 40s  # Tiempo inicial antes de verificar
    restart: unless-stopped

  # Kick API Microservice
  kick-api:
    build:
      context: ../KickApi
      dockerfile: Dockerfile
    container_name: kick-api
    ports:
      - "8003:8003"
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8003
      - LOG_LEVEL=INFO
      - TEMP_DIR=/tmp/kick_processing
      - CONVERTED_VIDEOS_DIR=/app/converted_videos
      - CACHE_EXPIRY_SECONDS=3600
      - CLEANUP_INTERVAL_SECONDS=300
      - WHISPER_MODEL=tiny
      - WHISPER_TIMEOUT=180
      - FFMPEG_TIMEOUT=300
      - DOWNLOAD_TIMEOUT=120
      - DEFAULT_QUALITY=medium
      - DEFAULT_PLATFORM=general
      - DEFAULT_FPS=30
    volumes:
      - /tmp/kick_processing:/tmp/kick_processing
      - kick_storage:/app/converted_videos
      - kick_temp:/app/temp
    networks:
      - reelify-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8003/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    depends_on:
      - clip-generator

volumes:
  temp_storage:
    driver: local
  kick_storage:
    driver: local
  kick_temp:
    driver: local
  video_downloads:
    driver: local

networks:
  reelify-network:
    driver: bridge
